# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaui', '0002_auto_20171216_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeddvapql',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaui.ExternalServer'),
        ),
    ]
