# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', 'custom_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(default='', max_length=100)),
                ('model_filename', models.CharField(default='', max_length=200)),
                ('queue', models.CharField(default='', max_length=300)),
                ('produces_labels', models.BooleanField(default=False)),
                ('produces_json', models.BooleanField(default=False)),
                ('produces_text', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomDetector',
            new_name='Detector',
        ),
        migrations.RenameModel(
            old_name='CustomIndexer',
            new_name='Indexer',
        ),
    ]
