# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvaapp', 'custom_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('original_pk', models.IntegerField()),
                ('deleter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deleter', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FederatedQueryResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('server_name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
                ('distance', models.FloatField(default=0.0)),
                ('results_metadata', models.TextField(default='')),
                ('results_available', models.BooleanField(default=False)),
                ('result_image_data', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_level', models.BooleanField(default=False)),
                ('start_frame_index', models.IntegerField()),
                ('end_frame_index', models.IntegerField()),
                ('metadata_text', models.TextField(default='')),
                ('metadata_json', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='scene',
            name='end_frame',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='source',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='start_frame',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='video',
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='scene',
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='query_float_vector',
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='query_int_vector',
        ),
        migrations.RemoveField(
            model_name='tevent',
            name='region',
        ),
        migrations.AddField(
            model_name='indexerquery',
            name='source_filter_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='indexerquery',
            name='vector',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='federated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
        migrations.AddField(
            model_name='region',
            name='materialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='png',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visua_query_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('A', 'Annotation'), ('D', 'Detection'), ('P', 'Polygon'), ('S', 'Segmentation'), ('T', 'Transform')], max_length=1),
        ),
        migrations.AlterField(
            model_name='segment',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
        migrations.AddField(
            model_name='tube',
            name='end_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_frame', to='dvaapp.Frame'),
        ),
        migrations.AddField(
            model_name='tube',
            name='end_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_region', to='dvaapp.Region'),
        ),
        migrations.AddField(
            model_name='tube',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
        migrations.AddField(
            model_name='tube',
            name='start_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_frame', to='dvaapp.Frame'),
        ),
        migrations.AddField(
            model_name='tube',
            name='start_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_region', to='dvaapp.Region'),
        ),
        migrations.AddField(
            model_name='tube',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
        migrations.AddField(
            model_name='federatedqueryresults',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Query'),
        ),
        migrations.AddField(
            model_name='federatedqueryresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedlabel',
            name='tube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Tube'),
        ),
    ]
