# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_auto_20170704_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visua_query_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
