# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='vdn_key',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='annotation',
            name='vdn_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNObject'),
        ),
        migrations.AddField(
            model_name='detection',
            name='vdn_key',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='detection',
            name='vdn_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNObject'),
        ),
    ]
