# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvaapp', '0001_auto_20170729_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVAPQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('I', 'Ingest'), ('V', 'Process'), ('Q', 'Query')], default='Q', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('image_data', models.BinaryField(null=True)),
                ('query_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('results_metadata', models.TextField(default='')),
                ('results_available', models.BooleanField(default=False)),
                ('federated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='user',
        ),
        migrations.AlterField(
            model_name='federatedqueryresults',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL'),
        ),
        migrations.AlterField(
            model_name='indexerquery',
            name='parent_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL'),
        ),
        migrations.AlterField(
            model_name='queryresults',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='parent_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL'),
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
