# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnotationTag',
        ),
        migrations.AddField(
            model_name='framelabel',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Annotation'),
        ),
        migrations.AddField(
            model_name='framelabel',
            name='label_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VLabel'),
        ),
    ]
