# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='start_index',
            field=models.IntegerField(default=0),
        ),
    ]
