# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlabel',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
