# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_annotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentries',
            name='entries_file_name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexentries',
            name='features_file_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
