# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_segment_start_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='segment_index',
            field=models.IntegerField(null=True),
        ),
    ]
