# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_auto_20170408_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlabel',
            name='vdn_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNObject'),
        ),
        migrations.AlterField(
            model_name='vlabel',
            name='source',
            field=models.CharField(choices=[('UI', 'User Interface'), ('DR', 'Directory Name'), ('AG', 'Algorithm'), ('VD', 'Visual Data Network')], default='UI', max_length=2),
        ),
    ]
