# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_auto_20170326_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='label_count',
            field=models.IntegerField(default=0),
        ),
    ]
