# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvaapp', '0002_auto_20170709_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('original_pk', models.IntegerField()),
                ('deleter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deleter', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
