# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_annotation_label_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framelabel',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='label_parent',
        ),
        migrations.RemoveField(
            model_name='framelabel',
            name='video',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='label_count',
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VLabel'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='source',
            field=models.TextField(default='user_interface'),
        ),
        migrations.DeleteModel(
            name='FrameLabel',
        ),
    ]
