# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 20:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_auto_20170412_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='query',
            name='excluded_indexers_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=[], size=None),
        ),
        migrations.AddField(
            model_name='query',
            name='excluded_videos_pk',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
