# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dvaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_auto_20170427_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='video',
        ),
        migrations.RemoveField(
            model_name='s3export',
            name='video',
        ),
        migrations.RemoveField(
            model_name='s3import',
            name='video',
        ),
        migrations.AddField(
            model_name='tevent',
            name='bucket',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tevent',
            name='clustering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Clusters'),
        ),
        migrations.AddField(
            model_name='tevent',
            name='event_type',
            field=models.CharField(choices=[('V', 'Video'), ('SE', 'S3 export'), ('SI', 'S3 import'), ('CL', 'Clustering'), ('E', 'Export as file')], default=dvaapp.models.Video, max_length=2),
        ),
        migrations.AddField(
            model_name='tevent',
            name='file_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tevent',
            name='key',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tevent',
            name='region',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='tevent',
            name='requester_pays',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Export',
        ),
        migrations.DeleteModel(
            name='S3Export',
        ),
        migrations.DeleteModel(
            name='S3Import',
        ),
    ]
