# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_vlabel_vdn_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.TextField(default=''),
        ),
    ]
