# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0003_auto_20170408_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='vdn_parent',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='vdn_parent',
        ),
        migrations.RemoveField(
            model_name='vdndataset',
            name='child_video',
        ),
        migrations.RemoveField(
            model_name='vlabel',
            name='vdn_parent',
        ),
        migrations.AddField(
            model_name='annotation',
            name='vdn_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDataset'),
        ),
        migrations.AddField(
            model_name='detection',
            name='vdn_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDataset'),
        ),
        migrations.AddField(
            model_name='video',
            name='vdn_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDataset'),
        ),
        migrations.AddField(
            model_name='vlabel',
            name='vdn_dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDataset'),
        ),
        migrations.DeleteModel(
            name='VDNObject',
        ),
    ]
