# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_auto_20170716_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='materialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='png',
            field=models.BooleanField(default=False),
        ),
    ]
