# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_auto_20170327_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='name',
        ),
    ]
