# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_auto_20170413_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='excluded_indexers_name',
            new_name='selected_indexers',
        ),
    ]
