# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_auto_20170409_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdnserver',
            name='token',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='vdnserver',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
