# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_tevent_start_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexerquery',
            name='source_filter_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
