# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_query_results_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIndexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(default='', max_length=100)),
                ('model_filename', models.CharField(default='', max_length=200)),
                ('input_layer_name', models.CharField(default='', max_length=300)),
                ('embedding_layer_name', models.CharField(default='', max_length=300)),
                ('embedding_layer_size', models.CharField(default='', max_length=300)),
                ('indexer_queue', models.CharField(default='', max_length=300)),
                ('retriever_queue', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
