# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_customindexer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='detections',
            new_name='segments',
        ),
        migrations.AddField(
            model_name='indexerquery',
            name='indexer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.CustomIndexer'),
        ),
    ]
