# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_auto_20170413_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevent',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tevent',
            name='errored',
            field=models.BooleanField(default=False),
        ),
    ]
