# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_auto_20170717_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tevent',
            name='region',
        ),
        migrations.AddField(
            model_name='region',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
    ]
