# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_auto_20170330_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlabel',
            unique_together=set([('source', 'label_name')]),
        ),
    ]
