# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_auto_20170803_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevent',
            name='parent_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL'),
        ),
    ]
