# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_auto_20170826_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='model_filename',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
