# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_auto_20170501_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='full_frame',
            field=models.BooleanField(default=False),
        ),
    ]
