# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0006_auto_20170413_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='excluded_videos_pk',
            new_name='excluded_index_entries_pk',
        ),
        migrations.AlterField(
            model_name='tevent',
            name='error_message',
            field=models.TextField(default='', null=True),
        ),
    ]
