# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0007_tevent_parent_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevent',
            old_name='arguments_json',
            new_name='arguments',
        ),
    ]
