# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0007_vdndataset_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdndataset',
            name='parent_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDataset'),
        ),
        migrations.AddField(
            model_name='vdndataset',
            name='parent_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
