# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0007_indexerquery_source_filter_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segment',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
            preserve_default=False,
        ),
    ]
