# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_appliedlabel_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='parent_segment_index',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
