# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_auto_20170411_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdndataset',
            name='parent_url',
        ),
    ]
