# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_auto_20170502_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevent',
            name='json_arguments',
            field=models.TextField(default='{}'),
        ),
    ]
