# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_auto_20170413_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_pays', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=300)),
                ('bucket', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('completed', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
    ]
