# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_auto_20170628_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentries',
            name='indexer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.CustomIndexer'),
        ),
    ]
