# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_remove_vdndataset_parent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='aws_key',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='aws_s3_bucket',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
