# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_tevent_json_arguments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevent',
            old_name='json_arguments',
            new_name='arguments_json',
        ),
    ]
