# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_s3import'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='LOPQ', max_length=50)),
                ('cluster_count', models.IntegerField()),
                ('components', models.IntegerField()),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('completed', models.BooleanField(default=False)),
                ('index_entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.IndexEntries')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
    ]
