# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_export'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexentries',
            unique_together=set([('video', 'features_file_name')]),
        ),
    ]
