# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0010_auto_20170412_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='aws_s3_bucket',
            new_name='aws_bucket',
        ),
    ]
