# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0010_auto_20170827_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevent',
            old_name='seconds',
            new_name='duration',
        ),
    ]
