# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0010_indexentries_indexer'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX region_text_index ON dvaapp_region USING GIN (to_tsvector('english', metadata_text || ' ' || object_name));
            CREATE INDEX frame_text_index ON dvaapp_frame USING GIN (to_tsvector('english', name || ' ' || subdir));
            CREATE INDEX label_text_index ON dvaapp_appliedlabel USING GIN (to_tsvector('english', label_name));
            """
        ),
    ]
