# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_auto_20170412_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='aws_region',
            field=models.CharField(default='', max_length=50),
        ),
    ]
