# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_auto_20170405_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdndataset',
            name='organization_url',
            field=models.TextField(default='Asdasda'),
            preserve_default=False,
        ),
    ]
