# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_textsearch_indexes'),
    ]

    operations = [
    ]
