# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='end_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_frame', to='dvaapp.Frame'),
        ),
        migrations.AddField(
            model_name='scene',
            name='start_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_frame', to='dvaapp.Frame'),
        ),
    ]
