# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0012_auto_20170806_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('set', models.CharField(max_length=200)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('label_name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('UI', 'User Interface'), ('DR', 'Directory Name'), ('AG', 'Algorithm'), ('VD', 'Visual Data Network')], default='UI', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Region')),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Segment')),
                ('tube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Tube')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.CreateModel(
            name='RegionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Region')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='TubeLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label')),
                ('tube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Tube')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='tube',
        ),
        migrations.RemoveField(
            model_name='appliedlabel',
            name='video',
        ),
        migrations.DeleteModel(
            name='AppliedLabel',
        ),
        migrations.AddField(
            model_name='framelabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Label'),
        ),
    ]
