# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0012_vdndataset_organization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdndataset',
            name='url',
        ),
        migrations.RemoveField(
            model_name='vdndataset',
            name='youtube_video',
        ),
    ]
