# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0012_auto_20170503_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentries',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
    ]
