# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0013_auto_20170807_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='label',
            name='label_name',
        ),
        migrations.RemoveField(
            model_name='label',
            name='region',
        ),
        migrations.RemoveField(
            model_name='label',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='label',
            name='source',
        ),
        migrations.RemoveField(
            model_name='label',
            name='tube',
        ),
        migrations.AlterField(
            model_name='label',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
    ]
