# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0013_indexentries_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevent',
            name='task_id',
            field=models.TextField(default=''),
        ),
    ]
