# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0014_auto_20170807_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='video',
        ),
    ]
