# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0014_tevent_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='task_id',
            field=models.TextField(null=True),
        ),
    ]
