# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0015_remove_label_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='framelabel',
            name='frame_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='framelabel',
            name='segment_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='framelabel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
        migrations.AddField(
            model_name='regionlabel',
            name='frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame'),
        ),
        migrations.AddField(
            model_name='regionlabel',
            name='frame_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='regionlabel',
            name='segment_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='regionlabel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
        migrations.AddField(
            model_name='segmentlabel',
            name='segment_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='segmentlabel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
        migrations.AddField(
            model_name='tubelabel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
    ]
