# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0015_auto_20170505_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.TextField()),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VLabel')),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='label',
        ),
        migrations.RemoveField(
            model_name='region',
            name='label_parent',
        ),
        migrations.AddField(
            model_name='appliedlabel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Region'),
        ),
        migrations.AddField(
            model_name='appliedlabel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
    ]
