# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0015_auto_20170418_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='m',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='clusters',
            name='sub',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='clusters',
            name='v',
            field=models.IntegerField(default=16),
        ),
    ]
