# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0015_retriever_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexerquery',
            old_name='source_filter_json',
            new_name='source_filters',
        ),
        migrations.AddField(
            model_name='indexerquery',
            name='retriever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Retriever'),
        ),
    ]
