# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0016_auto_20170418_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='metadata_json',
            field=models.TextField(default=''),
        ),
    ]
