# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0016_auto_20170807_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='set',
            field=models.CharField(default='', max_length=200),
        ),
    ]
