# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0017_annotation_metadata_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='detection',
        ),
    ]
