# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0017_auto_20170808_0446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('name', 'set')]),
        ),
    ]
