# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0018_auto_20170527_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
