# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0018_auto_20170808_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framelabel',
            name='segment_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='regionlabel',
            name='segment_index',
            field=models.IntegerField(null=True),
        ),
    ]
