# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0019_auto_20170808_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvapql',
            name='process_type',
            field=models.CharField(choices=[('S', 'Schedule'), ('V', 'Process'), ('Q', 'Query')], default='Q', max_length=1),
        ),
    ]
