# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0019_query_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDetector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=100)),
                ('model_filename', models.CharField(max_length=200)),
                ('vdn_parent', models.TextField(default='')),
                ('arguments', models.TextField(default='')),
            ],
        ),
    ]
