# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0020_auto_20170816_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedvideo',
            name='deleter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deleter', to=settings.AUTH_USER_MODEL),
        ),
    ]
