# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0020_customdetector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetector',
            name='algorithm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customdetector',
            name='model_filename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
