# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0021_auto_20170603_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetector',
            name='boxes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdetector',
            name='class_distribution',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customdetector',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customdetector',
            name='frames_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdetector',
            name='phase_1_log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customdetector',
            name='phase_2_log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customdetector',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
    ]
