# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0022_auto_20170605_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetector',
            name='name',
            field=models.CharField(default='initial_temp', max_length=100),
            preserve_default=False,
        ),
    ]
