# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 15:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvaapp', '0022_managementaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredDVAPQL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('S', 'Schedule'), ('V', 'Process'), ('Q', 'Query')], default='Q', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('script', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tevent',
            name='queue',
            field=models.CharField(default='', max_length=100),
        ),
    ]
