# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0023_customdetector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetector',
            name='class_names',
            field=models.TextField(default=''),
        ),
    ]
