# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0023_queryresults_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresults',
            name='detection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Detection'),
        ),
    ]
