# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0023_auto_20170817_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federatedqueryresults',
            name='query',
        ),
        migrations.RemoveField(
            model_name='federatedqueryresults',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dvapql',
            name='federated',
        ),
        migrations.AddField(
            model_name='storeddvapql',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='storeddvapql',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='FederatedQueryResults',
        ),
    ]
