# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0024_queryresults_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentries',
            name='approximate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexentries',
            name='contains_detections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexentries',
            name='contains_frames',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexentries',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexentries',
            name='detection_name',
            field=models.CharField(default='frame', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexentries',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
        ),
    ]
