# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0024_auto_20170818_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(choices=[('A', 'Annotation'), ('D', 'Detection'), ('P', 'Polygon'), ('S', 'Segmentation'), ('T', 'Transform')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='storeddvapql',
            name='process_type',
            field=models.CharField(choices=[('S', 'Schedule'), ('V', 'Process'), ('Q', 'Query')], db_index=True, default='Q', max_length=1),
        ),
    ]
