# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0024_customdetector_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetector',
            name='trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tevent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
    ]
