# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0025_auto_20170611_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDNDetector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(default='')),
                ('date_imported', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('description', models.TextField(default='')),
                ('download_url', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('aws_requester_pays', models.BooleanField(default=False)),
                ('aws_region', models.TextField(default='')),
                ('aws_bucket', models.TextField(default='')),
                ('aws_key', models.TextField(default='')),
                ('organization_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vdnserver',
            name='last_response_detectors',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='vdndetector',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNServer'),
        ),
    ]
