# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0026_auto_20170611_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdetector',
            name='vdn_parent',
        ),
        migrations.AddField(
            model_name='customdetector',
            name='vdn_detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.VDNDetector'),
        ),
    ]
