# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0026_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='queue_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
