# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 04:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0026_tevent_imported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='polygon_points_json',
        ),
        migrations.RemoveField(
            model_name='region',
            name='vdn_dataset',
        ),
        migrations.RemoveField(
            model_name='region',
            name='vdn_key',
        ),
        migrations.AddField(
            model_name='region',
            name='polygon_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
