# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0027_auto_20170822_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_index', models.IntegerField(null=True)),
                ('ingest_filename', models.CharField(max_length=500)),
                ('start_segment_index', models.IntegerField(null=True)),
                ('start_frame_index', models.IntegerField(null=True)),
                ('segments', models.IntegerField(null=True)),
                ('frames', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ingestlog',
            unique_together=set([('video', 'ingest_filename', 'ingest_index')]),
        ),
    ]
