# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0027_auto_20170611_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.IntegerField()),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('metadata', models.TextField(default='{}')),
                ('frame_count', models.IntegerField(default=0)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set([('video', 'segment_index')]),
        ),
    ]
