# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0027_externaldataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='task_id',
        ),
    ]
