# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0028_auto_20170617_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='keyframe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frame',
            name='t',
            field=models.FloatField(null=True),
        ),
    ]
