# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 06:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0029_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='metadata_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='annotation',
            name='name',
            field=models.TextField(default='unnamed_annotation'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='metadata_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
