# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0029_queryregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRegionIndexVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('query_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.QueryRegion')),
            ],
        ),
    ]
