# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0030_auto_20170320_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='metadata_json',
        ),
    ]
