# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0031_remove_annotation_metadata_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='full_frame',
            field=models.BooleanField(default=True),
        ),
    ]
