# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0034_auto_20171004_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepmodel',
            name='model_filename',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
