# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0035_auto_20171004_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DeepModel'),
        ),
    ]
