# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0040_tevent_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementaction',
            name='ping_index',
            field=models.IntegerField(null=True),
        ),
    ]
