# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0041_managementaction_ping_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VDNServer',
        ),
    ]
