# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0043_auto_20171215_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepmodel',
            old_name='additional_files',
            new_name='files',
        ),
    ]
