# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0044_auto_20171222_0539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lopqcodes',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='lopqcodes',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='lopqcodes',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='lopqcodes',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='lopqcodes',
            name='retriever',
        ),
        migrations.RemoveField(
            model_name='lopqcodes',
            name='video',
        ),
        migrations.DeleteModel(
            name='LOPQCodes',
        ),
    ]
