# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    initial = False
    dependencies = [('dvaapp', '0001_initial'),]

    operations = [
        # migrations.RunPython(forwards_func, reverse_func),
        migrations.RunSQL(
            """
            CREATE INDEX region_text_index_text ON dvaapp_region USING GIST (to_tsvector('english', text));
            CREATE INDEX region_text_index_object_name ON dvaapp_region USING GIST (to_tsvector('english', object_name));
            CREATE INDEX frame_text_index_name ON dvaapp_frame USING GIST (to_tsvector('english', name ));
            CREATE INDEX frame_text_index_subdir ON dvaapp_frame USING GIST (to_tsvector('english', subdir));
            CREATE INDEX label_text_index ON dvaapp_label USING GIST (to_tsvector('english', name));
            """
        ),
    ]
