# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdnapp', '0004_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='uploader',
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataset_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='annotation',
            name='server',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='annotation',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vdnapp.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vdnapp.Organization'),
            preserve_default=False,
        ),
    ]
