# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0007_remove_dataset_detections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('name', 'organization')]),
        ),
    ]
