# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0008_auto_20170405_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='url',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='youtube_video',
        ),
    ]
