# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0009_auto_20170405_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='aws_bucket',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='aws_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='aws_region',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='download_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='aws_bucket',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='aws_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='aws_region',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='download_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
