# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vdnapp', '0010_auto_20170405_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='description',
            new_name='metadata_text',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='Dataset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='aws_bucket',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='aws_key',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='aws_region',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='aws_requester_pays',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='dataset_name',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='vdn_server',
        ),
        migrations.AddField(
            model_name='annotation',
            name='dataset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vdnapp.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='full_frame',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='parent_frame_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
