# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0011_auto_20170409_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
