# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0012_annotation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='name',
        ),
        migrations.AddField(
            model_name='annotation',
            name='remote_dataset',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdnapp.Dataset'),
        ),
    ]
