# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0014_auto_20170411_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='remote_dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='parent_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='dataset',
            name='root',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
