# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0017_auto_20170411_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='user',
        ),
    ]
