# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0019_detector_indexer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='tfgraph_url',
        ),
        migrations.AddField(
            model_name='detector',
            name='aws_bucket',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detector',
            name='aws_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detector',
            name='aws_region',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detector',
            name='aws_requester_pays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detector',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='detector',
            name='download_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detector',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdnapp.Organization'),
        ),
    ]
