# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0020_auto_20170605_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='parent_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
