# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0022_auto_20170806_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detector',
            new_name='VDNRemoteDetector',
        ),
        migrations.DeleteModel(
            name='Indexer',
        ),
    ]
