# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdnapp', '0023_auto_20170825_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dataset',
            new_name='VDNRemoteDataset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
