# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0002_detector_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzer',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='indexer',
            name='indexer_queue',
        ),
        migrations.RemoveField(
            model_name='indexer',
            name='retriever_queue',
        ),
    ]
