# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0004_auto_20170826_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='class_index_to_strings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detector',
            name='detector_type',
            field=models.CharField(choices=[('T', 'Tensorflow'), ('Y', 'YOLO V2')], db_index=True, max_length=1, null=True),
        ),
    ]
