# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0005_auto_20170826_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='class_index_to_strings',
            new_name='class_index_to_string',
        ),
    ]
