# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0008_auto_20170826_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdndataset',
            name='parent_local',
        ),
        migrations.RemoveField(
            model_name='vdndataset',
            name='server',
        ),
        migrations.RemoveField(
            model_name='vdndetector',
            name='server',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='vdn_detector',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vdn_dataset',
        ),
        migrations.DeleteModel(
            name='VDNDataset',
        ),
        migrations.DeleteModel(
            name='VDNDetector',
        ),
    ]
