# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 16:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0009_auto_20170826_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdnserver',
            name='last_response_datasets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vdnserver',
            name='last_response_detectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
