# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0011_auto_20170828_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retriever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='indexer',
            name='shasum',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='retriever',
            name='indexer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Indexer'),
        ),
    ]
