# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0014_auto_20170829_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='retriever',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
