# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0019_auto_20170831_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='retriever',
            name='last_built',
            field=models.DateTimeField(null=True),
        ),
    ]
