# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0020_retriever_last_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='query',
        ),
    ]
