# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0021_remove_video_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryIndexVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
            ],
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='indexer',
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='parent_query',
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='retriever',
        ),
        migrations.RemoveField(
            model_name='indexerquery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='queryresults',
            name='indexerquery',
        ),
        migrations.AddField(
            model_name='queryresults',
            name='retrieval_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
        migrations.DeleteModel(
            name='IndexerQuery',
        ),
    ]
