# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 05:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0022_auto_20170901_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOPQCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('coarse', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None)),
                ('coarse_text', models.TextField(default='')),
                ('fine_text', models.TextField(default='')),
                ('searcher_index', models.IntegerField()),
                ('detection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Region')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame')),
                ('retriever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Retriever')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clustercodes',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='clustercodes',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='clustercodes',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='clustercodes',
            name='detection',
        ),
        migrations.RemoveField(
            model_name='clustercodes',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='clustercodes',
            name='video',
        ),
        migrations.DeleteModel(
            name='ClusterCodes',
        ),
        migrations.AlterUniqueTogether(
            name='lopqcodes',
            unique_together=set([('searcher_index', 'retriever')]),
        ),
        migrations.AlterIndexTogether(
            name='lopqcodes',
            index_together=set([('retriever', 'searcher_index')]),
        ),
    ]
