# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0027_worker_queue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='parent_frame_index',
            new_name='frame_index',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='parent_segment_index',
            new_name='segment_index',
        ),
    ]
