# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0030_queryregionindexvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryregionindexvector',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent'),
        ),
    ]
