# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0031_auto_20170913_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRegionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('algorithm', models.CharField(max_length=100)),
                ('distance', models.FloatField(default=0.0)),
                ('detection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Region')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Frame')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DVAPQL')),
                ('query_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.QueryRegion')),
                ('retrieval_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video')),
            ],
        ),
    ]
