# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 03:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0033_auto_20170920_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector_type', models.CharField(choices=[('T', 'Tensorflow'), ('Y', 'YOLO V2')], db_index=True, max_length=1, null=True)),
                ('mode', models.CharField(choices=[('T', 'Tensorflow'), ('C', 'Caffe'), ('P', 'Pytorch'), ('O', 'OpenCV'), ('M', 'MXNet')], db_index=True, default='T', max_length=1)),
                ('model_type', models.CharField(choices=[('I', 'Indexer'), ('D', 'Detector'), ('A', 'Analyzer'), ('S', 'Segmenter')], db_index=True, default='I', max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(default='', max_length=100)),
                ('shasum', models.CharField(max_length=40, null=True, unique=True)),
                ('model_filename', models.CharField(default='', max_length=200)),
                ('input_layer_name', models.CharField(default='', max_length=300)),
                ('embedding_layer_name', models.CharField(default='', max_length=300)),
                ('embedding_layer_size', models.CharField(default='', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('arguments', models.TextField(default='')),
                ('phase_1_log', models.TextField(default='')),
                ('phase_2_log', models.TextField(default='')),
                ('class_distribution', models.TextField(default='')),
                ('class_names', models.TextField(default='')),
                ('frames_count', models.IntegerField(default=0)),
                ('boxes_count', models.IntegerField(default=0)),
                ('trained', models.BooleanField(default=False)),
                ('class_index_to_string', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('url', models.CharField(default='', max_length=200)),
                ('additional_files', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('produces_labels', models.BooleanField(default=False)),
                ('produces_json', models.BooleanField(default=False)),
                ('produces_text', models.BooleanField(default=False)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.TEvent')),
            ],
        ),
        migrations.DeleteModel(
            name='Analyzer',
        ),
        migrations.RemoveField(
            model_name='detector',
            name='source',
        ),
        migrations.AlterField(
            model_name='indexentries',
            name='indexer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.DeepModel'),
        ),
        migrations.DeleteModel(
            name='Detector',
        ),
        migrations.DeleteModel(
            name='Indexer',
        ),
    ]
