# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0037_auto_20171022_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexentries',
            old_name='source',
            new_name='event',
        ),
    ]
