# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0046_trainingset'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
