# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0047_workerrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeepModel',
            new_name='TrainedModel',
        ),
    ]
