# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0048_auto_20171224_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='built',
            field=models.BooleanField(default=False),
        ),
    ]
