# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0049_trainingset_built'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerRequest',
        ),
    ]
