# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 10:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0050_delete_workerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='boxes_count',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='class_distribution',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='class_index_to_string',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='class_names',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='embedding_layer_name',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='embedding_layer_size',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='frames_count',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='input_layer_name',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='phase_1_log',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='phase_2_log',
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
