# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0052_auto_20171230_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='retriever',
            name='approximator_shashum',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
