# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0053_retriever_approximator_shashum'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexentries',
            name='approximator_shashum',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='retriever',
            name='indexer_shasum',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='retriever',
            name='approximator_shashum',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
