# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0054_auto_20171230_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexentries',
            old_name='approximator_shashum',
            new_name='approximator_shasum',
        ),
        migrations.RenameField(
            model_name='retriever',
            old_name='approximator_shashum',
            new_name='approximator_shasum',
        ),
    ]
