# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0055_auto_20171230_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexentries',
            unique_together=set([('video', 'entries_file_name')]),
        ),
    ]
