# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-31 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0057_tevent_task_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='task_group_id',
            field=models.IntegerField(default=-1),
        ),
    ]
