# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0058_auto_20171231_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retriever',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='retriever',
            name='last_built',
        ),
    ]
