# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0059_auto_20180101_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retriever',
            name='algorithm',
            field=models.CharField(choices=[('L', 'LOPQ'), ('E', 'Exact'), ('P', 'PCA')], db_index=True, default='E', max_length=1),
        ),
    ]
