# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0060_auto_20180101_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retriever',
            name='algorithm',
            field=models.CharField(choices=[('L', 'LOPQ'), ('E', 'Exact')], db_index=True, default='E', max_length=1),
        ),
    ]
