# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0061_auto_20180101_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryindexvector',
            name='event',
        ),
        migrations.DeleteModel(
            name='QueryIndexVector',
        ),
    ]
