# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0062_auto_20180107_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvapql',
            name='image_data',
        ),
    ]
