# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0063_remove_dvapql_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvapql',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
